[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/admin.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[context.production.environment]
  NODE_ENV = "production"