[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[dev]
  functions = "netlify/functions"
  publish = "."
  command = "echo 'Starting local development server...'"
  port = 8888

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/admin.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"

# Redirects for SPA-like behavior
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/admin/"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/members"
  to = "/members.html"
  status = 200

[[redirects]]
  from = "/members/"
  to = "/members.html"
  status = 200

# Ensure cache headers apply to redirected paths too
[[headers]]
  for = "/members"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/admin"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"